SET SERVEROUTPUT ON
DECLARE
    vTexto VARCHAR2(100):= 'Hello World em PL/SQL';
BEGIN
    DBMS_OUTPUT.PUT_LINE(vTexto);
EXCEPTION
    WHEN OTHERS
    THEN
        DBMS_OUTPUT.PUT_LINE('ERRO ORACLE: ' || SQLCODE || SQLERRM);
END;
